### ISSUE TITLE
Keep global state?

### ISSUE THREAD

**Issue by jlev** [spacedogXYZ/crush2020#1]
Currently using component-level state and hooks for the form, and getting weird effects if someone goes back/forward or clicks to internal links and then back to form. Consider Redux

**Comment by camdenlee** [comment]
@jlev I can take this on. Can you point me to the areas in the application you'd want to use global state? I did a quick search for `useState` and found a few items, but all of them might not necessitate global state.

This might not need the complexity of Redux and React Context could do the trick instead. Do you have a strong preference?

**Comment by jlev** [comment]
Thanks @camdenlee! The form has a context provider in https://github.com/spacedogXYZ/crush2020/blob/master/src/components/form/context.js, which is used in the PlanForm component. That's pretty close to redux style (reducers, etc), and works to keep track of user state when they progress normally through the flow.

But, I'm seeing some weird issues when someone navigates away from the form (to eg, Methodology) and then back. Progress is lost, which is not a deal breaker but isn't a great experience. The worst problem is that when you reload a form step (even the first one), it renders with a broken layout which doesn't make sense to me...

- After navigating to form/vote directly
<img width="1306" alt="Screen Shot 2020-09-14 at 9 38 57 AM" src="https://user-images.githubusercontent.com/294964/93113574-37218300-f66e-11ea-94a9-caf06e6357c1.png">

- After starting to fill out the form and then reloading
<img width="1218" alt="Screen Shot 2020-09-14 at 9 39 13 AM" src="https://user-images.githubusercontent.com/294964/93113590-3b4da080-f66e-11ea-8542-2efe7ddacc46.png">

**Comment by jlev** [comment]
Fixed with #19
