### ISSUE TITLE
Stuck on the "Pick a competitive state and help win big nationally" page.

### ISSUE THREAD

**Issue by ACPK** [spacedogXYZ/crush2020#23]
I'm on the "Pick a competitive state and help win big nationally" page and have selected a few states.

However, I only get the next "Please select your answers" when I click the next button despite how many states I select.

https://www.crush2020.org/form/reach
![Screen Shot 2020-10-27 at 5 57 58 PM](https://user-images.githubusercontent.com/2019893/97366589-f4161a80-187d-11eb-9cd8-caf002723bc7.png)

**Comment by jkestner** [comment]
It works for me when I start from the Make a Plan button on the front page, but not when I start on this page. Maybe you lost your session? Even reloading the page will do that.

**Comment by ACPK** [comment]
@jkestner - Not using cookies if that helps.

**Comment by ACPK** [comment]
@jkestner - Still not able to get it to work

**Comment by jlev** [comment]
Yeah, the session state handling did leave something to be desired...

I'm going to close this because the site is no longer under active development.
